version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: rkasymaliev
      POSTGRES_DB: appdb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
 
  app:
    build: .
    container_name: application
    ports:
      - 3000:3000
    restart: always
    links:
      - db
  
  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - app
